# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret

  mongo-app:
    image: mongo-app
    ports:
      - 30043:30043
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: secret
      MONGO_HOST: mongo
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 30043
